#!/bin/zsh
#
# File: updateinstall
# Description: Install (or update if installed) classes and packages for latex.
# Author: Andy Holt
# Date: Wed 12 Aug 2015 18:14

# latex classes directory
clsd=$HOME/Projects/LaTeXClasses

# create TEXMFHOME tree
tree=`kpsewhich -var-value TEXMFHOME`
latexd=$tree/tex/latex
if [[ ! -d $tree ]]; then
    mkdir -p $latexd
fi

# install or update article class
if [[ ! -d $latexd/adharticle ]]; then
    mkdir $latexd/adharticle
fi
cp $clsd/adharticle.cls $latexd/adharticle/adharticle.cls

# install or update outline class
if [[ ! -d $latexd/adhoutline ]]; then
    mkdir $latexd/adhoutline
fi
cp $clsd/adhoutline.cls $latexd/adhoutline/adhoutline.cls

# install or update sernotes class
if [[ ! -d $latexd/adhsernotes ]]; then
    mkdir $latexd/adhsernotes
fi
cp $clsd/adhsernotes.cls $latexd/adhsernotes/adhsernotes.cls

# install or update sertrans class for sermon transcripts
if [[ ! -d $latexd/adhsertrans ]]; then
    mkdir $latexd/adhsertrans
fi
cp $clsd/adhsertrans.cls $latexd/adhsertrans/adhsertrans.cls

# install or update compact notes class
if [[ ! -d $latexd/adhcompnotes ]]; then
    mkdir $latexd/adhcompnotes
fi
cp $clsd/adhcompnotes.cls $latexd/adhcompnotes/adhcompnotes.cls

# install or update polyglot class
if [[ ! -d $latexd/polyglot ]]; then
    mkdir $latexd/polyglot
fi
cp $clsd/polyglot.cls $latexd/polyglot/polyglot.cls

# install or update symbols package
if [[ ! -d $latexd/adhsymbols ]]; then
    mkdir $latexd/adhsymbols
fi
cp $clsd/adhsymbols.sty $latexd/adhsymbols/adhsymbols.sty

# install or update paratext package
if [[ ! -d $latexd/paratext ]]; then
    mkdir $latexd/paratext
fi
cp $clsd/paratext.sty $latexd/paratext/paratext.sty

# install or update handout class
if [[ ! -d $latexd/adhhandout ]]; then
    mkdir $latexd/adhhandout
fi
cp $clsd/adhhandout.cls $latexd/adhhandout/adhhandout.cls

# install or update generic doc class
if [[ ! -d $latexd/adhdoc ]]; then
    mkdir $latexd/adhdoc
fi
cp $clsd/adhdoc.cls $latexd/adhdoc/adhdoc.cls

# install or update didasko package
if [[ ! -d $latexd/didasko ]]; then
    mkdir $latexd/didasko
fi
cp $clsd/didasko.sty $latexd/didasko/didasko.sty

# install or update lecture notes class
if [[ ! -d $latexd/adhlecnotes ]]; then
    mkdir $latexd/adhlecnotes
fi
cp $clsd/adhlecnotes.cls $latexd/adhlecnotes/adhlecnotes.cls

# install or update sbts paper class
if [[ ! -d $latexd/sbtspaper ]]; then
    mkdir $latexd/sbtspaper
fi
cp $clsd/sbtspaper.cls $latexd/sbtspaper/sbtspaper.cls

# install or update sbts precis class
if [[ ! -d $latexd/sbtsprecis ]]; then
    mkdir $latexd/sbtsprecis
fi
cp $clsd/sbtsprecis.cls $latexd/sbtsprecis/sbtsprecis.cls

# install or update sbts church history reading assignment class
if [[ ! -d $latexd/sbtshistread ]]; then
    mkdir $latexd/sbtshistread
fi
cp $clsd/sbtshistread.cls $latexd/sbtshistread/sbtshistread.cls

# install or update sbts book review class
if [[ ! -d $latexd/sbtsreview ]]; then
    mkdir $latexd/sbtsreview
fi
cp $clsd/sbtsreview.cls $latexd/sbtsreview/sbtsreview.cls


# install or update bible reference package
if [[ ! -d $latexd/adhbibleref ]]; then
    mkdir $latexd/adhbibleref
fi
cp $clsd/adhbibleref.sty $latexd/adhbibleref/adhbibleref.sty

# install or update GNT manuscript package
if [[ ! -d $latexd/gntm ]]; then
    mkdir $latexd/gntm
fi
cp $clsd/gntm.cls $latexd/gntm/gntm.cls

# install or update Hebrew manuscript package
if [[ ! -d $latexd/hbms ]]; then
    mkdir $latexd/hbms
fi
cp $clsd/hbms.cls $latexd/hbms/hbms.cls

# install or update letter class
if [[ ! -d $latexd/adhletter ]]; then
    mkdir $latexd/adhletter
fi
cp $clsd/adhletter.cls $latexd/adhletter/adhletter.cls
cp $clsd/adhlettinfopersonal.sty $latexd/adhletter/adhlettinfopersonal.sty

mktexlsr $tree

echo "Updated latex classes and packages."
